### ISSUE TITLE
Switch to Github actions?

### ISSUE THREAD

**Issue by tomac4t** [citizenlab/test-lists#604]
Looks something wrong with Travis CI. Recently, I notice that it doesn't build for Pull Request (in this repo). Maybe should switch to Github actions? Like: 
```yaml
name: check
on: 
  push:
    paths:
    - "lists/*"
  pull_request:
    paths:
    - "lists/*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: check
      run: python scripts/lint-lists.py lists/
```
